name: "Pre-review Tests"

on: [push, pull_request]

jobs:
  pretest:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: install
      run: |
        pip install -U pip wheel
        pip install flake8 autopep8

    - name: flake8
      run: |
        flake8

    - name: autopep8
      run: |
        autopep8 -r . --global-config .pep8 --diff | tee check_autopep8
        test ! -s check_autopep8
